"""
Base Strategy
─────────────
Abstract base class that all trading strategies must implement.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum

import pandas as pd


class Signal(Enum):
    """Trading signal generated by a strategy."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass
class TradeSignal:
    """Complete trade signal with all details needed to place an order."""
    signal: Signal
    symbol: str
    price: float  # Current/entry price
    stop_loss: float  # Stop-loss price
    target: float  # Target/take-profit price
    quantity: int = 0  # Filled in by risk manager
    reason: str = ""  # Human-readable reason for the signal
    strategy: str = ""  # Strategy name that generated this
    confluence_score: float = 0.0  # 0-100 confidence score
    confluence_details: dict = field(default_factory=dict)  # Component breakdown
    rsi: float | None = None  # RSI at signal time (used by risk manager)
    entry_atr: float = 0.0  # ATR at signal time (used for trailing stop)
    confirming_strategies: list = field(default_factory=list)  # Names of strategies that agreed (set by orchestrator)

    @property
    def risk_per_share(self) -> float:
        """How much we risk per share (distance to stop-loss)."""
        return abs(self.price - self.stop_loss)

    @property
    def reward_per_share(self) -> float:
        """Potential reward per share (distance to target)."""
        return abs(self.target - self.price)

    @property
    def risk_reward_ratio(self) -> float:
        """Reward-to-risk ratio. We want >= 2.0."""
        risk = self.risk_per_share
        if risk == 0:
            return 0
        return self.reward_per_share / risk


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    Every strategy must implement:
    - name: Strategy identifier
    - analyze(): Takes OHLCV data with optional HTF data and regime context
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Unique name for this strategy."""
        ...

    @abstractmethod
    def analyze(
        self,
        df: pd.DataFrame,
        symbol: str,
        df_htf: pd.DataFrame = None,
        regime=None,
    ) -> TradeSignal:
        """
        Analyze market data and generate a trading signal.

        Args:
            df: OHLCV DataFrame with indicators already calculated (primary TF)
            symbol: Stock symbol being analyzed
            df_htf: Higher-timeframe DataFrame (e.g. 15min) for trend confirmation
            regime: MarketRegime enum (from market_regime module)

        Returns:
            TradeSignal with BUY, SELL, or HOLD
        """
        ...

    def _hold(self, symbol: str, reason: str = "") -> TradeSignal:
        """Convenience method to return a HOLD signal."""
        return TradeSignal(
            signal=Signal.HOLD,
            symbol=symbol,
            price=0,
            stop_loss=0,
            target=0,
            reason=reason,
            strategy=self.name,
        )
